#!/bin/bash

function changeEnvironment() {
  if [ "$1" == "alpha" ]; then
    echo "s#/alpha#/$1#g"
  elif [ "$1" == "beta" ]; then
    echo "s#/alpha#/$1#g"
  else
    exit
  fi
}

function currentEnvironment() {
  if [ "$1" == "alpha" ]; then
    echo "beta"
  elif [ "$1" == "beta" ]; then
    echo "alpha"
  else
    exit
  fi
}

function changeFiles() {
  echo "Type the repo you want to modify"
  read repo
  echo "Type alpha or beta"
  read environment
  currentEnvironment=$(currentEnvironment $environment)
  newEnvironment=$(changeEnvironment $environment)

  cd ../mpmobile-ios_$repo/Pod/Classes

  if [ "$environment" == "alpha" ] || [ "$environment" == "beta" ]; then
    find . -type f -print0 | xargs -0 grep -l "/$currentEnvironment" | while read line; do
      perl -pi -e $newEnvironment $line
      echo "Succesfully changed $(basename $line) environment to $environment"
    done
    echo "================================="
    echo "All the services of $repo are in $environment"
    echo "================================="
  else
    echo "Error"
  fi
}

changeFiles
