#!/bin/bash

function move() {
  if [ "$1" == "mpmobile-ios_wallet" ]; then
    #Podfile is in this folder
    cd ../$1
  else
    #Podfile is in Example folder
    cd ../$1/Example
  fi
}

function podAction() {
    #Executes the pod install or pod update
    pod $1
}

function fullRepoName() {
  #read short repository name and return full name
  local fullRepoName="mpmobile-ios_$1"
  echo "$fullRepoName"
}

echo "Write "update" or "install" space and the repository you want"
read podAction repo
fullRepo=$(fullRepoName $repo)
move $fullRepo
podAction $podAction
